### ISSUE TITLE
Is mk1 cabin hatch compatitable with Restock

### ISSUE THREAD

**Issue by harrytherocketeer** [skalou/Mk1-Cabin-Hatch#1]

**Comment by skalou** [comment]
yes it is but please don't open issue for this and use the forum instead:
[https://forum.kerbalspaceprogram.com/index.php?/topic/151443-1xx-mk1-cabin-hatch-v101-18-december-2020/](https://forum.kerbalspaceprogram.com/index.php?/topic/151443-1xx-mk1-cabin-hatch-v101-18-december-2020/)
